task4_DropdownList/task4/dropdown_list/urls.py
from django.contrib import admin
from django.urls import path

from .views import *

urlpatterns = [
    path('', PersonList.as_view(), name ='person_list'),
    path('add/', PersonCreate.as_view(), name ='person_add'),
    path('<int:pk>/', PersonUpdate.as_view(), name ='person_update'),
    path('ajax/load-cities/', load_cities, name='ajax_load_cities'),  # <-- this one here


]

task4_DropdownList/task4/task4/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('dropdown_list.urls'))
]

task4_DropdownList/task4/dropdown_list/models.py
from django.db import models

# Create your models here.
class Country(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class City(models.Model):
    country = models.ForeignKey(Country , on_delete=models.CASCADE)
    name  =models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Person(models.Model):
    name  = models.CharField(max_length=200)
    birthday =models.DateField(null=True ,blank=True)
    country = models.ForeignKey(Country ,on_delete=models.CASCADE)
    city =models.ForeignKey(City , on_delete=models.CASCADE)

    def __str__(self):
        return self.name

task4_DropdownList/task4/dropdown_list/forms.py
from django import forms
from .models import *

class PersonForm(forms.ModelForm):
    class Meta:
        model =Person
        fields =('name', 'birthday', 'country', 'city')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()
        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

task4_DropdownList/task4/dropdown_list/views.py
from django.shortcuts import render
from django.views.generic import ListView , CreateView ,UpdateView
from django.urls import reverse_lazy

from .models import *
from .forms import *
# Create your views here.

class PersonList(ListView):
    model = Person
    context_object_name = 'people'
    template_name ='person_list.html'

class PersonCreate(CreateView):
    model = Person
    #fields =('name', 'birthday', 'country', 'city')
    form_class =PersonForm
    template_name ='person_form.html'
    success_url = reverse_lazy('person_list')

class PersonUpdate(UpdateView):
    model = Person
    #fields =('name', 'birthday', 'country', 'city')
    form_class =PersonForm
    template_name ='person_form.html'
    success_url = reverse_lazy('person_list')

def load_cities(request):
    country_id = request.GET.get('country')
    cities = City.objects.filter(country_id=country_id).order_by('name')
    return render(request, 'city_dropdown_list_options.html', {'cities': cities})

task4_DropdownList/task4/dropdown_list/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% block content%}
    {% endblock %}
  </body>
</html>

task4_DropdownList/task4/dropdown_list/templates/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
{{ city.name }}
{% endfor %}

task4_DropdownList/task4/dropdown_list/templates/person_form.html
{% extends "base.html" %}
{% block content %}
<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Save</button>
  <a href="{% url 'person_list' %}">Nevermind</a>
</form>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
 <script>
   $("#id_country").change(function () {
     var url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
     var countryId = $(this).val();  // get the selected country ID from the HTML input

     $.ajax({                       // initialize an AJAX request
       url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
       data: {
         'country': countryId       // add the country id to the GET parameters
       },
       success: function (data) {   // `data` is the return of the `load_cities` view function
         $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
       }
     });

   });
 </script>
{% endblock %}

task4_DropdownList/task4/dropdown_list/templates/person_list.html
{% extends 'base.html'%}
{% block content%}
{% for p in people%}
<a href="{% url 'person_update' p.pk %}">{{p.name}}</a>
{%endfor%}
{% endblock%}